PROGRAM MPI9a
USE MPI
INTEGER :: nprocs,rank,ierr
INTEGER :: PP(1:2000),PPF(1:2000),displs(8)
INTEGER :: INI,FIN,NUME,NM
DOUBLE PRECISION :: CPR,REM
NM=1000
CALL MPI_INIT(ierr)
CALL MPI_COMM_SIZE(MPI_COMM_WORLD,nprocs,ierr)
CALL MPI_COMM_RANK(MPI_COMM_WORLD,rank,ierr)

	CPR = NM/nprocs
	REM = CPR-INT(CPR)
	INI = rank*CPR
	FIN = INI+CPR+NINT(REM*nprocs)
	IF(rank.EQ.(nprocs-1))FIN = NM
	NUME = FIN-INI
WRITE(*,*)rank,INI,FIN,NUME
	 DO 100 i=1,NUME
	 	PP(i) = i*1000
100 CONTINUE
!CALL MPI_GATHER(PP,NUME,MPI_INTEGER,PPF,NUME,MPI_INTEGER,0,MPI_COMM_WORLD,ierr)
CALL MPI_ALLGATHER(PP,NUME,MPI_INTEGER,PPF,NUME,MPI_INTEGER,MPI_COMM_WORLD,ierr)
IF(rank.eq.1) THEN
	DO 200 i=1,NM
		WRITE(*,*)i,PP(i),PPF(i)
200 CONTINUE
END IF

CALL MPI_FINALIZE(ierr)
END PROGRAM

